# ===================================
#  List Behavior Config
# ===================================

list: ~/plugins/devnull/main/models/menu/columns.yaml
modelClass: Devnull\Main\Models\Menu

title: devnull.menu:lang.controllers.menu_manager

recordUrl: devnull/main/menus/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 50

showTree: true
toolbar:
  buttons: list_toolbar
  search:
    prompt: backend::lang.list.search_prompt