# ===================================
#  Form Behavior Config
# ===================================

name: devnull.main::lang.controllers.menu_name

form: ~/plugins/devnull/main/models/menu/fields.yaml
modelClass: Devnull\Main\Models\Menu
defaultRedirect: devnull/main/menus

create:
  title: devnull.manin::lang.controllers.menu_form_create
  redirect: devnull/main/menus/update/:id
  redirectClose: devnull/main/menus
  flash-save: devnull.main::lang.form.flashcreate

update:
  title: devnull.main::lang.form.update
  redirect: devnull/main/menus
  redirectClose: devnull/main/menus
  flash-save: devnull.main::lang.form.flashupdate
  flash-delete: devnull.main::lang.form.flashdelete

preview:
  title: devnull.main::lang.form.preview